before_script:
 - opam switch -y remove gitrunner ||  echo "Opam environment clean up"
 - opam switch -y create gitrunner ocaml-base-compiler.4.10.0
 - opam install . -y --deps-only
 - eval $(opam env)
build:
  stage: build
  script:
  - make
  - make test
  - make doc
